name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Transform Figma Tokens JSON to something Style Dictionary can read
        run: npx token-transformer tokens.json tokens.json
      - name: Convert tokens according to Style Dictionary config
        run: npx style-dictionary build --config config.json
      - run: git status
      - name: Cache tokens
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "<>"
      - name: Get cached tokens
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
      - name: Bump version and commit
        run: npm version patch
      - run: git status
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
      - run: git push
        env:
          github-token: ${{ secrets.GIT_TOKEN }}
